version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/backend-439402/devongimage:1.2
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    env_file:
      - ./.env.prod
    ports:
      - 3000:3000